### PR TITLE
fix flutter_tex_js.dart flickering

### PR DESCRIPTION
**Pull request by Guilherme-ds-Garcia**
fix infinity flickering loop of FutureBuilder making the LayoutBuilder rebuild the FutureBuilder

### CODE REVIEW

**Comment by amake** [comment]
The image is intended to be re-rendered (thus the flicker) when the layout changes because the width of the layout can affect the rendering result: e.g. when `displayMode` is false, the width of the layout determines where the text will break.

There are cases (such as `displayMode: true`) where layout changes shouldn't cause a re-render; I can try to address that, but I'm not a fan of the approach in this PR.

Could you describe how you're using TexImage so I get a better idea of the use case? Please provide a minimal code sample that illustrates the flickering.

**Comment by carloshgsilva** [comment]
Sorry for making this a PR, it should have been placed in the Issues.
It was supposed to be a quick fix.
PS: I'm friend of @Rockzeraaa

BTW Your package is the only one that is really worth using

Exemple that makes the loop:
```dart
Scaffold(
      body: Center(child: TexImage("1+2+3")),
);
```

Exemple that works:
```dart
Scaffold(
      body: SizedBox.expand(child: TexImage("1+2+3")),
);
```

**Comment by amake** [comment]
Thanks for the information.

I don't get a loop when I try your sample, but I do get two renders:

1. Initial render
2. Display of rendered image changes the layout, causing `LayoutBuilder` to run again, causing another render

But since the result of the second render is the same as the first, the loop should (and does, for me) end there. I'm not sure why it would go on forever.

I will fix it so that rendering is not called again when the parameters are unchanged

**Comment by amake** [comment]
I should add that you've correctly identified the best workaround for the moment: make sure the width of the `TexImage`'s parent is wider than the eventual rendered result.

**Comment by carloshgsilva** [comment]
I haven't tested but I think I found something.
You might be using an Flutter version greater or equals than 1.18.X

According to https://github.com/flutter/flutter/wiki/Changelog#v118x they have changed the `LayoutBuilder`

I'm using Flutter 1.17.5 so I think this might be the problem.

**Comment by amake** [comment]
> I'm using Flutter 1.17.5 so I think this might be the problem.

Thanks, that was indeed the difference. Now I've reproduced the flicker.

**Comment by carloshgsilva** [comment]
Yup, I tested with 1.20.X and it worked fine.

**Comment by amake** [comment]
Thanks for your report. I just released 0.1.5 with a fix. Please let know if there are any further issues.

**Pull request closed without merging**
